config/routes.rb
Rails.application.routes.draw do

  resources :profiles
  devise_for :users
  get '/users/activities', to: 'users#user_activities'
  resources :users
  resources :courses
  resources :institutions
  resources :teachers
  resources :attachments
  resources :activities
  resources :subjects

  root 'activities#index'

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
	belongs_to :activity
	
	mount_uploader :file, AttachmentFileUploader

end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_attachment, only: [:show, :edit, :update, :destroy]

  # GET /attachments
  # GET /attachments.json
  def index
    @attachments = Attachment.all
  end

  # GET /attachments/1
  # GET /attachments/1.json
  def show
  end

  # GET /attachments/new
  def new
    @attachment = Attachment.new
  end

  # GET /attachments/1/edit
  def edit
  end

  # POST /attachments
  # POST /attachments.json
  def create
    @attachment = Attachment.new(attachment_params)

    respond_to do |format|
      if @attachment.save
        format.html { redirect_to @attachment, notice: 'Attachment was successfully created.' }
        format.json { render :show, status: :created, location: @attachment }
      else
        format.html { render :new }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attachments/1
  # PATCH/PUT /attachments/1.json
  def update
    respond_to do |format|
      if @attachment.update(attachment_params)
        format.html { redirect_to @attachment, notice: 'Attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @attachment }
      else
        format.html { render :edit }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attachments/1
  # DELETE /attachments/1.json
  def destroy
    @attachment.destroy
    respond_to do |format|
      format.html { redirect_to attachments_url, notice: 'Attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attachment
      @attachment = Attachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attachment_params
      params.require(:attachment).permit(:activity_id, :file)
    end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/views/attachments/_form.html.erb
<%= simple_form_for @attachment, html: {multipart: true} do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :activity %>
    <%= f.input :file, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/attachments/edit.html.erb
<h1>Editing Attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @attachment %> |
<%= link_to 'Back', attachments_path %>

app/views/attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Anexos</h1>

<table class="table table-striped table-responsive table-bordered">
  <thead>
    <tr>
      <th>Atividade</th>
      <th>Usuário</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attachments.each do |attachment| %>
      <tr>
        <td><%= attachment.activity.name %></td>
        <td><%= attachment.activity.user.email %></td>
        <td>
          <div class="btn-group pull-right">
            <%= link_to 'Exibir', attachment, class: 'btn btn-sm btn-default' %>
            <%= link_to 'Editar', edit_attachment_path(attachment), class: 'btn btn-sm btn-default' %>
            <%= link_to 'Excluir', attachment, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
seiscentos
<br>

<%= link_to 'New Attachment', new_attachment_path %>

app/views/attachments/new.html.erb
<h1>New Attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', attachments_path %>

app/views/attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Activity:</strong>
  <%= @attachment.activity_id %>

  <strong>File</strong>
  <%= image_tag @attachment.file_url.to_s %>
</p>

<%= link_to 'Edit', edit_attachment_path(@attachment) %> |
<%= link_to 'Back', attachments_path %>