config/routes.rb
Rails.application.routes.draw do

  resources :profiles
  devise_for :users
  get '/users/activities', to: 'users#user_activities'
  resources :users
  resources :courses
  resources :institutions
  resources :teachers
  resources :attachments
  resources :activities
  resources :subjects

  root 'activities#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    alias_action :create, :read, :update, :destroy, :to => :crud

    if user.role == 'admin'
      can :manage, Activity
    else
      can :read, Activity
      can [:update, :destroy], Activity, :user_id => user.id
    end


    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/activity.rb
class Activity < ActiveRecord::Base
	has_many :attachments, dependent: :destroy
	belongs_to :subject
	belongs_to :user

	enum activity_type: [:exam, :test, :list, :code]

	accepts_nested_attributes_for :attachments

	def self.activity_type_for_select
		activity_types.map do |activity_type, _|
		  [I18n.t("activerecord.attributes.#{model_name.i18n_key}.activity_types.#{activity_type}"), activity_type]
		end
	end

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
	belongs_to :activity
	
	mount_uploader :file, AttachmentFileUploader

end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :subjects
	belongs_to :institution
end

app/models/institution.rb
class Institution < ActiveRecord::Base
	has_many :courses
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	has_many :activities
	belongs_to :teacher
	belongs_to :course
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	has_many :subjects
end

app/models/user.rb
class User < ActiveRecord::Base
  before_create :set_user_role
  before_create :build_default_profile
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :activities
  has_one :profile

  ROLES = %w[admin moderator publisher banned].freeze

  private
    def set_user_role
      self.role = 'publisher'
    end

    def build_default_profile
      build_profile
      true
    end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :institution_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def user_activities
    @activities = Activity.where(user_id: current_user.id)
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :role)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def user_profile_of(user)
		Profile.find_by_user_id(user)
	end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Miprova</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=PT+Sans+Narrow|Roboto" rel="stylesheet">
</head>
<body>
<% if user_signed_in? %>
  <nav class="navbar navbar-default nav-main">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">miProva</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="col-md-6">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <!-- <li><%= link_to 'Matérias', subjects_path %></li> -->
            <li><%= link_to 'Atividades', activities_path %></li>
            <!-- <li><%= link_to 'Anexos', attachments_path %></li> -->
            <!-- <li><%= link_to 'Professores', teachers_path %></li> -->
            <!-- <li><%= link_to 'Cursos', courses_path %></li> -->
            <!-- <li><%= link_to 'Instituições', institutions_path %></li> -->
            <!-- <li><%= link_to 'Usuários', users_path %></li> -->
          </ul>
    <!--         <ul class="nav navbar-nav pull-right">
            <li>
              Hello, <%= link_to current_user.email, user_profile_of(current_user) %>

              <span class="label label-default"><%= current_user.role.humanize %></span>
            </li>
            <li><%= link_to "Sair", destroy_user_session_path, :method => :delete %></li>
          </ul> -->
        </div><!-- /.navbar-collapse -->
      </div>
      <div class="col-md-4 pull-right">
        <div class="media">
            <%= link_to user_profile_of(current_user), class: 'pull-left' do %>
                <img class="media-object dp img-circle" src="http://placehold.it/50x50"">
            <% end %>
            <div class="media-body">
                <h5 class="media-heading">
                  <%= user_profile_of(current_user).name %>
                  <small><%= link_to "Sair", destroy_user_session_path, :method => :delete %></small>
                </h5>
                <h6>Software Developer at <a href="http://gridle.in">Gridle.in</a></h6>
            </div>
        </div>
      </div>
        
    </div><!-- /.container-fluid -->
  </nav>
<% end %>

<div class="container">
  <%= yield %>
</div>
</body>
</html>